-- Add test comments for series "Bọ Ngựa"
-- This migration adds sample external comments for the series
-- SKIPPED: This migration requires users to exist first
-- Will be handled by data seeding scripts instead
